**Numpy**

In [4]:
val1 = 7
print(val1 * 2)

14


In [3]:
list1 = [2,4,7,9,3]
print(list1)
print()
print(list1 * 2)

[2, 4, 7, 9, 3]

[2, 4, 7, 9, 3, 2, 4, 7, 9, 3]


In [6]:
list2 = [[4,3,3,2,1] , [4,5,4,3,1]]
print(list2)
print(list2 * 2)

[[4, 3, 3, 2, 1], [4, 5, 4, 3, 1]]
[[4, 3, 3, 2, 1], [4, 5, 4, 3, 1], [4, 3, 3, 2, 1], [4, 5, 4, 3, 1]]


In [8]:
import numpy as np

In [16]:
arr1 = np.array([2,4,7,9,3])
print(arr1)

[2 4 7 9 3]


In [17]:
print(arr1 * 2)

[ 4  8 14 18  6]


In [18]:
arr2 = np.array([[4,3,3,2,1] , [7,5,4,3,5] , [5,2,9,1,6]])
print(arr2)

[[4 3 3 2 1]
 [7 5 4 3 5]
 [5 2 9 1 6]]


In [22]:
arr3 = np.array([[4,3,3,2,1] , [5,4,3,5,np.nan] , [5,2,9,1,6]])
print(arr3)

[[ 4.  3.  3.  2.  1.]
 [ 5.  4.  3.  5. nan]
 [ 5.  2.  9.  1.  6.]]


In [24]:
arr4 = np.array([[4,3,3,2,1] , [7,5.5,4,3,5] , [5,2,9,1,6]])
print(arr4)

[[4.  3.  3.  2.  1. ]
 [7.  5.5 4.  3.  5. ]
 [5.  2.  9.  1.  6. ]]


In [29]:
arr5 = np.array([[4,3,3,'2',1] , [7,5.5,4,3,5] , [5,2,9,1,6]])
print(arr5)

[['4' '3' '3' '2' '1']
 ['7' '5.5' '4' '3' '5']
 ['5' '2' '9' '1' '6']]


In [30]:
print(type(np.nan))

<class 'float'>


In [32]:
print(arr1)

[2 4 7 9 3]


In [34]:
print(arr1.shape)
print(arr1.ndim)
print(arr1.size)

(5,)
1
5


In [35]:
print(arr2)

[[4 3 3 2 1]
 [7 5 4 3 5]
 [5 2 9 1 6]]


In [38]:
print(arr2.shape)
print(arr2.ndim)
print(arr2.size)

(3, 5)
2
15


In [55]:
print(arr2)

[[4 3 3 2 1]
 [7 5 4 3 5]
 [5 2 9 1 6]]


In [56]:
print(np.sum(arr2))
print(np.prod(arr2))
print(np.min(arr2))
print(np.max(arr2))
print(np.mean(arr2))
print(np.std(arr2))
print(np.argmin(arr2))  #argument for minimum
print(np.argmax(arr2))

60
81648000
1
9
4.0
2.160246899469287
4
12


In [43]:
#axis = 0 => for each column

print(np.sum(arr2 , axis = 0))
print(np.prod(arr2 , axis = 0))
print(np.min(arr2 , axis = 0))
print(np.max(arr2 , axis = 0))
print(np.mean(arr2, axis = 0))
print(np.std(arr2 , axis = 0))
print(np.argmin(arr2 , axis = 0))  #argument for minimum
print(np.argmax(arr2 , axis = 0))

[16 10 16  6 12]
[140  30 108   6  30]
[4 2 3 1 1]
[7 5 9 3 6]
[5.33333333 3.33333333 5.33333333 2.         4.        ]
[1.24721913 1.24721913 2.62466929 0.81649658 2.1602469 ]
[0 2 0 2 0]
[1 1 2 1 2]


In [44]:
#axis = 1 => for each row

print(np.sum(arr2 , axis = 1))
print(np.prod(arr2 , axis = 1))
print(np.min(arr2 , axis = 1))
print(np.max(arr2 , axis = 1))
print(np.mean(arr2, axis = 1))
print(np.std(arr2 , axis = 1))
print(np.argmin(arr2 , axis = 1))  #argument for minimum
print(np.argmax(arr2 , axis = 1))

[13 24 23]
[  72 2100  540]
[1 3 1]
[4 7 9]
[2.6 4.8 4.6]
[1.0198039  1.32664992 2.87054002]
[4 3 3]
[0 0 2]


In [45]:
#standard deviation

marks = np.array([34,35,12,45,23,25,27,29,31,33,37,7,9,20])

print(marks)

[34 35 12 45 23 25 27 29 31 33 37  7  9 20]


In [47]:
mean_marks = marks.mean()
print(mean_marks)

26.214285714285715


In [50]:
var_marks = ((marks - mean_marks)**2).mean()
print(var_marks)

114.45408163265304


In [51]:
std_marks = var_marks**0.5
print(std_marks)

10.698321439957441


In [52]:
#1st standard deviation
upper_limit_1 = mean_marks + std_marks
lower_limit_1 = mean_marks - std_marks

print(upper_limit_1)
print(lower_limit_1)

36.912607154243155
15.515964274328274


In [53]:
#2nd standard deviation
upper_limit_2 = mean_marks + 2*std_marks
lower_limit_2 = mean_marks - 2*std_marks

print(upper_limit_2)
print(lower_limit_2)

47.6109285942006
4.817642834370833


In [54]:
#3rd standard deviation
upper_limit_3 = mean_marks + 3*std_marks
lower_limit_3 = mean_marks - 3*std_marks

print(upper_limit_3)
print(lower_limit_3)

58.30925003415804
-5.88067860558661


In [58]:
print(np.zeros((4,3)))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [59]:
print(np.ones((4,3)))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [60]:
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
