In [1]:
import numpy as np

In [7]:
arr1 = np.array([[4,3,3,2,1] , [7,5,4,3,5] , [5,2,9,1,6]])
print(arr1)

[[4 3 3 2 1]
 [7 5 4 3 5]
 [5 2 9 1 6]]


In [10]:
arr1[2,2] = 19

In [11]:
print(arr1)

[[ 4  3  3  2  1]
 [ 7  5  4  3  5]
 [ 5  2 19  1  6]]


In [8]:
print(arr1[0,0])

4


In [2]:
print(np.zeros((4,3)))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [3]:
print(np.ones((4,3)))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [5]:
print(np.eye(4))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [13]:
arr2 = np.zeros((3,3))
print(arr2)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [16]:
#how to create a matrix using user input values

for i in range(0,3):
    user_input = int(input("Enter a number"))

    arr2[0,i] = user_input

Enter a number 3
Enter a number 4
Enter a number 7


In [17]:
print(arr2)

[[3. 4. 7.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [19]:
print(arr1)

[[ 4  3  3  2  1]
 [ 7  5  4  3  5]
 [ 5  2 19  1  6]]


In [20]:
print(arr1.reshape(5,3))

[[ 4  3  3]
 [ 2  1  7]
 [ 5  4  3]
 [ 5  5  2]
 [19  1  6]]


In [21]:
print(arr1.T)

[[ 4  7  5]
 [ 3  5  2]
 [ 3  4 19]
 [ 2  3  1]
 [ 1  5  6]]


* 3x + 2y + 5z = 15
* x + y + z = 10
* 2x + 2y + 7z = 25

In [22]:
A = np.array([[3,2,5] , [1,1,1] , [2,2,7]])
print(A)

[[3 2 5]
 [1 1 1]
 [2 2 7]]


In [23]:
X = np.array([['x'] , ['y'] , ['z']])
print(X)

[['x']
 ['y']
 ['z']]


In [24]:
B = np.array([[15],[10],[25]])
print(B)

[[15]
 [10]
 [25]]


In [25]:
#A.X = B
#X = inv(A).B

In [27]:
A_inv = np.linalg.inv(A)
print(A_inv)

[[ 1.  -0.8 -0.6]
 [-1.   2.2  0.4]
 [-0.  -0.4  0.2]]


In [29]:
X = np.dot(A_inv , B)
print(X)

[[-8.]
 [17.]
 [ 1.]]
